"use strict";
const fs = require("node:fs");
const assert = require("node:assert/strict");
const {initializeTestEnvironment, assertSucceeds, assertFails} = require("@firebase/rules-unit-testing");
const F = require("firebase/firestore");
const M = require("../inventory.js");
const H = require("../history.js");
const projectId = "demo-almox";
const pause = ms => new Promise(resolve => setTimeout(resolve, ms));
async function until(fn) { for(let i=0;i<300;i++){ if(fn()) return; await pause(30); } throw new Error("Timeout aguardando Firebase"); }
(async () => {
  const env = await initializeTestEnvironment({projectId, firestore: {host:"127.0.0.1",port:8088,rules:fs.readFileSync("tests/firebase/firestore.rules","utf8")}});
  const publicDb = env.unauthenticatedContext().firestore();
  const viewer = env.authenticatedContext("viewer"), admin = env.authenticatedContext("administrator");
  const adminDb = admin.firestore(), viewerDb = viewer.firestore();
  const main = db => F.doc(db,"warehouses/main");
  const shelf = M.defaultState().shelves[0]; shelf.id = "first";
  const metadata = revision => ({version:1,revision,historyId:"revision-"+revision,shelfIds:["first"],warehousePhoto:"",updatedBy:"administrator",updatedAt:F.serverTimestamp()});
  function audit(batch,db,revision,overrides={}) {
    batch.set(F.doc(db,"history/revision-"+revision),{revision,actorUid:"administrator",actorName:"",actorEmail:"",createdAt:F.serverTimestamp(),events:H.diff({warehousePhoto:"",shelves:[]},{warehousePhoto:"",shelves:[shelf]}),...overrides});
  }
  try {
    await env.clearFirestore();
    await env.withSecurityRulesDisabled(context => F.setDoc(F.doc(context.firestore(),"admins/administrator"),{enabled:true}));
    await assertFails(F.setDoc(F.doc(publicDb,"admins/intruder"),{enabled:true}));
    await assertFails(F.setDoc(F.doc(viewerDb,"admins/viewer"),{enabled:true}));
    await assertFails(F.setDoc(F.doc(adminDb,"admins/viewer"),{enabled:true}));
    await assertFails(F.getDoc(F.doc(publicDb,"admins/administrator")));
    await assertFails(F.getDoc(F.doc(viewerDb,"admins/administrator")));
    await assertFails(F.getDocs(F.collection(adminDb,"admins")));
    await assertSucceeds(F.getDoc(F.doc(viewerDb,"admins/viewer")));
    const batch = F.writeBatch(adminDb); batch.set(main(adminDb),metadata(1)); batch.set(F.doc(adminDb,"warehouses/main/shelves/first"),shelf);
    audit(batch,adminDb,1);await assertSucceeds(batch.commit());
    await assertSucceeds(F.getDoc(main(publicDb)));
    await assertSucceeds(F.getDocs(F.collection(publicDb,"warehouses/main/shelves")));
    await assertFails(F.setDoc(main(publicDb),metadata(2)));
    await assertFails(F.setDoc(main(viewerDb),metadata(2)));
    await assertFails(F.setDoc(F.doc(viewerDb,"warehouses/main/shelves/first"),{...shelf,name:"Invasão"}));
    await assertFails(F.deleteDoc(F.doc(publicDb,"warehouses/main/shelves/first")));
    await assertFails(F.setDoc(F.doc(adminDb,"warehouses/main/shelves/first"),{...shelf,name:"Sem revisão"}));
    await assertFails(F.setDoc(main(adminDb),metadata(1)));
    const changed = F.writeBatch(adminDb);
    changed.set(main(adminDb),metadata(2)); changed.set(F.doc(adminDb,"warehouses/main/shelves/first"),{...shelf,name:"Atualizada"});
    audit(changed,adminDb,2);await assertSucceeds(changed.commit());
    await assertFails(F.deleteDoc(main(adminDb)));
    await assertSucceeds(F.getDocs(F.collection(publicDb,"history")));
    await assertFails(F.updateDoc(F.doc(adminDb,"history/revision-1"),{actorName:"Outra pessoa"}));
    await assertFails(F.deleteDoc(F.doc(adminDb,"history/revision-1")));
    const fakeLog=F.writeBatch(adminDb);fakeLog.set(main(adminDb),metadata(3));audit(fakeLog,adminDb,3,{actorEmail:"outra@example.com"});await assertFails(fakeLog.commit());
    const missingLog=F.writeBatch(adminDb);missingLog.set(main(adminDb),metadata(3));await assertFails(missingLog.commit());

    console.log("OK: leitura pública; somente administrador escreve; autopromoção e revisão inválida bloqueadas.");
    const photo='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=';
    const imageDoc=db=>F.doc(db,"photos/test-photo");
    const imageData={data:photo,updatedBy:"administrator",updatedAt:F.serverTimestamp()};
    await assertFails(F.setDoc(imageDoc(publicDb),imageData));
    await assertFails(F.setDoc(imageDoc(viewerDb),{...imageData,updatedBy:"viewer"}));
    await assertSucceeds(F.setDoc(imageDoc(adminDb),imageData));
    assert.equal((await F.getDoc(imageDoc(publicDb))).data().data,photo);
    await assertFails(F.setDoc(imageDoc(adminDb),imageData));
    await assertFails(F.setDoc(F.doc(adminDb,"photos/oversize"),{...imageData,data:'data:image/jpeg;base64,'+'A'.repeat(260000)}));
    await assertFails(F.setDoc(F.doc(adminDb,"photos/invalid"),{...imageData,data:'data:text/html;base64,AAAA'}));
    await assertFails(F.deleteDoc(imageDoc(viewerDb)));
    await assertFails(F.getDocs(F.collection(publicDb,"photos")));
    await env.withSecurityRulesDisabled(context => F.setDoc(F.doc(context.firestore(),"admins/administrator"),{enabled:false}));
    await assertFails(F.setDoc(main(adminDb),metadata(3)));
    await assertFails(F.setDoc(F.doc(adminDb,"photos/revoked"),imageData));
    await env.withSecurityRulesDisabled(context => F.setDoc(F.doc(context.firestore(),"admins/administrator"),{enabled:true}));
    const failed=F.writeBatch(adminDb);failed.set(main(adminDb),metadata(3));failed.set(F.doc(adminDb,"photos/rejected"),{...imageData,data:"inválida"});
    await assertFails(failed.commit());
    assert.equal((await F.getDoc(main(publicDb))).data().revision,2);
    assert.equal((await F.getDoc(F.doc(publicDb,"photos/rejected"))).exists(),false);
    console.log("OK: fotos no Firestore, leitura pública, tamanho e formato, escrita protegida e revogação.");
    // Exercita o adaptador real contra Firestore/Auth, sem credenciais de produção.
    await env.clearFirestore();
    global.window = global;
    global.Inventory = M;
    global.InventoryHistory = H;
    global.location = {hostname:"127.0.0.1"};
    Object.defineProperty(global,"navigator",{value:{onLine:true},configurable:true});
    global.addEventListener = () => {};
    global.ALMOX_FIREBASE_CONFIG = {apiKey:"demo-key",authDomain:projectId+".firebaseapp.com",projectId,storageBucket:projectId+".appspot.com",appId:"demo-app"};
    global.ALMOX_FIREBASE_EMULATORS = true;
    let source = fs.readFileSync("firebase-client.js","utf8");
    source = source.replace('import(SDK + "firebase-" + name + ".js")','import("firebase/" + name)');
    new Function(source)();
    let record, session; const errors=[];
    await AlmoxCloud.init({onState:r=>record=r,onSession:s=>session=s,onError:e=>errors.push(e)});
    await until(()=>session.ready);
    await assert.rejects(()=>AlmoxCloud.saveState(M.defaultState(),0),/administradores/);
    const A = await import("firebase/auth"), app = await import("firebase/app");
    const auth = A.getAuth(app.getApp());
    const credential = await A.createUserWithEmailAndPassword(auth,"owner@example.com","test-password-123");
    await until(()=>session.user?.uid===credential.user.uid);
    await assert.rejects(()=>AlmoxCloud.saveState(M.defaultState(),0),/administradores/);
    await env.withSecurityRulesDisabled(context => F.setDoc(F.doc(context.firestore(),"admins",credential.user.uid),{enabled:true}));
    await until(()=>session.admin);
    const next = M.clone(record.state);
    next.shelves[0].items.push({id:"cement",row:"A",start:23,span:2,name:"Cimento",quantity:5,unit:"sc",asset:"PAT-1",notes:"",photo,updatedAt:new Date().toISOString()});
    const saved = await AlmoxCloud.saveState(next,0);
    assert.equal(saved.revision,1); await until(()=>record.revision===1);
    assert.equal(record.state.shelves[0].items[0].name,"Cimento");
    await assert.rejects(()=>AlmoxCloud.saveState(next,0),/atualizado/);
    const bad = M.clone(next); bad.shelves[0].items[0].quantity=0;
    await assert.rejects(()=>AlmoxCloud.saveState(bad,1),/Quantidade/);
    const savedShelf=await F.getDoc(F.doc(publicDb,"warehouses/main/shelves",next.shelves[0].id));
    const reference=savedShelf.data().items[0].photo;
    assert.match(reference,/^photo:/);
    assert.equal((await F.getDoc(F.doc(publicDb,"photos",reference.slice(6)))).data().data,photo);
    assert.equal(record.state.shelves[0].items[0].photo,photo);
    const after = M.clone(record.state); after.shelves[0].items[0].quantity=7;
    await AlmoxCloud.saveState(after,1); await until(()=>record.revision===2);
    assert.equal((await F.getDoc(F.doc(publicDb,"warehouses/main/shelves",next.shelves[0].id))).data().items[0].photo,reference);
    const expanded = M.clone(record.state);
    expanded.shelves.push({...M.defaultState().shelves[0],id:"second-shelf",name:"Segunda"});
    await AlmoxCloud.saveState(expanded,2); await until(()=>record.revision===3);
    const reduced=M.clone(record.state);reduced.shelves.pop();
    await AlmoxCloud.saveState(reduced,3); await until(()=>record.revision===4);
    assert.equal((await F.getDoc(F.doc(publicDb,"warehouses/main/shelves/second-shelf"))).exists(),false);
    const without=M.clone(record.state);without.shelves[0].items[0].photo="";
    await AlmoxCloud.saveState(without,4);await until(()=>record.revision===5);
    assert.equal((await F.getDoc(F.doc(publicDb,"photos",reference.slice(6)))).exists(),true);
    const warehouse=M.clone(record.state);warehouse.warehousePhoto=photo;
    await AlmoxCloud.saveState(warehouse,5);await until(()=>record.revision===6);
    assert.equal(record.state.warehousePhoto,photo);
    assert.match((await F.getDoc(main(publicDb))).data().warehousePhoto,/^photo:/);
    const history=await AlmoxCloud.getHistory();
    assert.equal(history.entries.length,6);
    assert.equal(history.entries[0].actorEmail,"owner@example.com");
    assert(history.entries.find(log=>log.revision===2).events.some(e=>e.changes.some(c=>c.field==="quantity"&&c.before===5&&c.after===7)));
    assert(history.entries.find(log=>log.revision===5).events.some(e=>e.changes.some(c=>c.field==="photo"&&c.before===reference&&c.after==="")));
    assert.equal(await AlmoxCloud.getPhoto(reference),photo);
    console.log("OK: histórico atômico, identidade, antes/depois e foto antiga preservada.");

    const run=require("node:util").promisify(require("node:child_process").execFile);
    const cold=await run(process.execPath,["tests/fixtures/firebase-public-reader.cjs"],{timeout:20000,windowsHide:true});console.log(cold.stdout.trim());
    await env.withSecurityRulesDisabled(context => F.setDoc(F.doc(context.firestore(),"admins",credential.user.uid),{enabled:false}));
    await until(()=>!session.admin);
    await assert.rejects(()=>AlmoxCloud.saveState(warehouse,6),/administradores/);
    await AlmoxCloud.logout(); await until(()=>!session.user);
    assert.equal(errors.length,0,errors.join("\n"));
    console.log("OK: adaptador real, login no emulador, permissão, sincronização, conflito e revogação.");
  } finally {
    await env.cleanup();
  }
})().then(()=>process.exit(0)).catch(error=>{console.error(error);process.exit(1);});

